name: Test with Docker

on:
  workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Add crypto key to config file
      run: echo "crypto_key_value=$crypto_key">> ./src/main/resources/_config.properties
      env: 
        crypto_key: ${{ secrets.CRYPTO_KEY }}
    - name: Pull selenoid chrome image
      run: docker pull selenoid/chrome:latest
    - name: Create network
      run: docker network create selenoid
    - name: Run docker-compose
      run: docker-compose up&
    - name: Run tests
      run: mvn clean -Dsuite=article test
