name: Test res manual start

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses:  actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Start Selenoid Server
        uses: Xotabu4/selenoid-github-action@v2
      - name: Build with Maven
        run: mvn clean -Dsuite=HeaderTest test
