name: Test res manual start

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses:  actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.2.0
      - name: Start selenoid
        uses: Xotabu4/selenoid-github-action@v2
      - run: chrome --version
      - name: Build with Maven
        run: mvn clean -Dsuite=actionability test
  
